---
galaxy_info:
  role_name: chrony
  namespace: lit
  author: Lightning IT
  description: Configure chrony NTP client on RHEL/EL systems.
  company: Lightning IT
  license: GPL-2.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - rhel
    - chrony
    - ntp
    - time
dependencies: []
