---
chrony_manage: true
chrony_manage_package: true
chrony_service_manage: true
chrony_makecache: true

chrony_packages:
  - chrony
chrony_pools:
  - "pool.ntp.org iburst"
chrony_servers: []
chrony_driftfile: /var/lib/chrony/drift
chrony_makestep: "1.0 3"
