---
baseline_packages_present:
  - curl
  - vim
  - jq
  - tar
  - bash-completion

baseline_timezone: Etc/UTC
baseline_locale: en_US.UTF-8

baseline_chrony_manage: true
baseline_chrony_pools:
  - "pool.ntp.org iburst"
baseline_chrony_servers: []
baseline_chrony_driftfile: /var/lib/chrony/drift
baseline_chrony_makestep: "1.0 3"

# Optional sysctl key/value map, e.g.:
# baseline_sysctl:
#   net.ipv4.ip_forward: 0
#   net.ipv4.conf.all.rp_filter: 1
baseline_sysctl: {}
