---
# Desired hostname (prefer inventory_hostname if not set)
hostname_fqdn: "{{ inventory_hostname }}"

# Manage /etc/hosts entry for 127.0.1.1
hostname_manage_etc_hosts: true

# Which IP to use for the local hostname line
hostname_etc_hosts_ip: "127.0.1.1"

# Add short hostname alias as second token
hostname_add_shortname: true
