---
galaxy_info:
  role_name: podman
  namespace: lit
  author: Lightning IT
  company: Lightning IT
  description: Install Podman tooling and prepare container registries config.
  license: GPL-2.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - podman
    - containers
    - rhel

dependencies: []
