---
- name: Enable necessary repos for RHEL
  ansible.builtin.import_tasks: repos.yml
  when: ansible_os_family == "RedHat"

- name: Install fail2ban
  ansible.builtin.package:
    name: "{{ fail2ban_packages }}"
    state: present

- name: Copy filters in filter.d
  ansible.builtin.copy:
    src: "{{ fail2ban_filterd_path }}"
    dest: /etc/fail2ban/filter.d/
    owner: root
    group: root
    mode: "0640"
  when:
    - fail2ban_filterd_path is defined
  notify:
    - Restart fail2ban

- name: Configure fail2ban.local
  ansible.builtin.template:
    src: fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    mode: "0640"
  notify:
    - Restart fail2ban

- name: Configure jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0640"
  notify:
    - Restart fail2ban

- name: Stat auth log file
  ansible.builtin.stat:
    path: /var/log/auth.log
  register: fail2ban_auth

- name: Touch auth log file
  ansible.builtin.file:
    path: /var/log/auth.log
    state: touch
    mode: "0640"
  when:
    - fail2ban_auth.stat.exists is defined
    - not fail2ban_auth.stat.exists

- name: Start and enable fail2ban
  ansible.builtin.service:
    name: "{{ fail2ban_service }}"
    state: started
    enabled: true
  when: fail2ban_manage_service | bool
