---
galaxy_info:
  role_name: gui
  namespace: lit
  author: Lightning IT
  description: Install a GUI stack on RHEL 9 (GNOME or XFCE).
  company: Lightning IT
  license: GPL-2.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions: ["9"]
  galaxy_tags:
    - rhel
    - gui
    - desktop
    - gnome
    - xfce
dependencies: []
