---
- name: Ensure firewalld is installed
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Ensure firewalld is enabled and running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  when: firewalld_manage_service | bool

- name: Enable services
  ansible.posix.firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ firewalld_services | default([]) }}"
  when:
    - firewalld_manage_service | bool
    - firewalld_services | length > 0

- name: Enable ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ firewalld_ports | default([]) }}"
  when:
    - firewalld_manage_service | bool
    - firewalld_ports | length > 0
