---
galaxy_info:
  role_name: automatic_updates
  namespace: lit
  author: Ren√© Osorio
  description: Configure weekly automatic OS updates via cron for RHEL systems.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"

  platforms:
    - name: EL
      versions:
        - "9"

  galaxy_tags:
    - modulix
    - rhel
    - updates
    - security
    - cron
    - automation

dependencies: []
